version: '3.8'

services:
  install:
    build:
      context: ./
    volumes:
      - base:/opt/application
      - www:/var/www/html
      - nginx-config:/etc/nginx
      - crontabs-postup:/etc/crontabs-postup

  api:
    restart: always
    build:
      context: packages/api
    env_file:
      - packages/api/production.env
    volumes:
      - base:/opt/application
      - nginx-config:/etc/nginx
      - /data/portal-storage:/data/storage
    networks:
      backend-network:
        ipv4_address: 10.11.0.100
    depends_on:
      install:
        condition: service_completed_successfully

  web:
    build:
      context: packages/web
    volumes:
      - base:/opt/application
      - www:/var/www/html
      - nginx-config:/etc/nginx
    depends_on:
      install:
        condition: service_completed_successfully

  mongo:
    image: mongo:latest
    restart: always
    networks:
      backend-network:
        ipv4_address: 10.11.0.90
    volumes:
      - /data/portal-db:/data/db

  nginx:
    image: nginx
    restart: always
    volumes:
      - www:/var/www/html
      - nginx-config:/etc/nginx
    ports:
      - '8082:80'
    networks:
      - backend-network
    depends_on:
      web:
        condition: service_completed_successfully

  postup:
    build:
      context: postup
    restart: always
    networks:
      - backend-network
    volumes:
      - /data/portal-backup:/data/backup
      - crontabs-postup:/etc/crontabs

volumes:
  www:
  base:
  nginx-config:
  crontabs-postup:

networks:
  backend-network:
    ipam:
      driver: default
      config:
        - subnet: 10.11.0.0/16
